name: Security

on: [ push, pull_request ]

jobs:
  scan:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Scan using grype
        uses: anchore/scan-action@v6.1.0
        with:
          path: "."
          by-cve: true
          output-format: table

